### PR TITLE
fix build for arm

### PR DESCRIPTION
**Pull request by zachaller**
fixes: https://github.com/argoproj-labs/argocd-extensions/issues/15

Signed-off-by: zachaller <zachaller@users.noreply.github.com>

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Comment by nlamirault** [comment]
do you think you could create a new release `v0.2.0` ?

**Comment by crenshaw-dev** [comment]
@nlamirault there's one running now, but it's taking a long time, and I don't see logs: https://github.com/argoproj-labs/argocd-extensions/actions/runs/3379643519/jobs/5611556993

I might stop and recreate it. We need v0.2.0 at Intuit for security fixes, so we'll get this done.  :-)

**Comment by nlamirault** [comment]
Great @crenshaw-dev !

**Comment by crenshaw-dev** [comment]
https://github.com/argoproj-labs/argocd-extensions/pkgs/container/argocd-extensions/48554680?tag=v0.2.0

🚀

**Pull request merged**
